/* hello_triangle.c*/
#include <GLES3/gl3.h>
#include <stdlib.h>
#include "egl_utils.h"
#include "hello_triangle.h"


GLuint load_shader(GLenum type, const char * shader_src) {
  GLuint shader;
  GLint compiled;

  shader = glCreateShader(type);

  switch (glGetError()) {
  case 0:
    LOGE("error creating a shader object");
    return 0;
  case GL_INVALID_ENUM:
    LOGE("Shader type %d is not accepted value", type);
    return 0;
  }

  // load the shader
  glShaderSource(shader, 1, &shader_src, 0x00);

  switch (eglGetError()) {    
  case GL_INVALID_VALUE:
    // is generated if shader is not a value generated by OpenGL.
    // or if count is less than 0.
    LOGE("GL invalid value");
    return 0;
  case GL_INVALID_OPERATION:
    // is generated if shader is not a shader object.
    LOGE("GL invalid value");
    return 0;
  }

  // compile the shader
  glCompileShader(shader);
  switch (eglGetError()) {    
  case GL_INVALID_VALUE:
    // is generated if shader is not a value generated by OpenGL.
    // or if count is less than 0.
    LOGE("GL invalid value");
    return GL_FALSE;
  case GL_INVALID_OPERATION:
    // is generated if shader is not a shader object.
    LOGE("GL invalid value");
    return 0;
  }

  switch (eglGetError()) {    
  case GL_INVALID_VALUE:
    // is generated if shader is not a value generated by OpenGL.
    // or if count is less than 0.
    LOGE("GL invalid value");
    return GL_FALSE;
  case GL_INVALID_OPERATION:
    // is generated if shader is not a shader object.
    LOGE("GL invalid value");
    return 0;
  }  

  // check the compile status  
  glGetShaderiv(shader, GL_COMPILE_STATUS, &compiled);
  
  if (!compiled) {
    GLint info_len = 0;

    glGetShaderiv(shader, GL_INFO_LOG_LENGTH, &info_len);

    if (info_len > 1) {
      char *info_log = malloc (sizeof(char) * info_len);
      glGetShaderInfoLog(shader, info_len, NULL, info_log);
      LOGE("Error compiling program %s", info_log);
      free(info_log);
    }

    glDeleteShader(shader);
    return 0;
  }

  return shader;
  
}


// initialize the shader and program object aka gl objects
int init(struct egl_context * context) { 
  struct program_data * pd = context->shader_program_data;
  char vertex_shader_str[] =
    "#version 300 es\n"
    "layout(location = 0) in vec4 vPosition;\n"
    "void main()\n"
    "{\n"
    "gl_Position = vPosition;\n"
    "}\n";

  char fragment_shader_str[] =
    "#version 300 es\n"
    "precision mediump float;\n"
    "out vec4 fragColor;\n"
    "void main()\n"
    "{\n"
    "fragColor = vec4 ( 1.0, 0.0, 0.0, 1.0 );\n"
    "}\n";

  GLuint vertex_shader, fragment_shader, program_object;
  GLint linked;

  // load the vertex and fragment shader
  vertex_shader = load_shader(GL_VERTEX_SHADER, vertex_shader_str);
  fragment_shader = load_shader(GL_FRAGMENT_SHADER, fragment_shader_str);

  // create the shader program pbject
  program_object = glCreateProgram();

  if (program_object == 0) {
    LOGE("No program object");
    return 0;
  }

  glAttachShader(program_object, vertex_shader);
  glAttachShader(program_object, fragment_shader);

  // link the program
  glGetProgramiv(program_object, GL_LINK_STATUS, &linked);

  if (!linked) {
    GLint info_len = 0;
    glGetProgramiv(program_object, GL_INFO_LOG_LENGTH, &info_len);

    if (info_len > 1) {
      char * info_log = malloc (sizeof(char) * info_len);
      glGetProgramInfoLog(program_object, info_len, 0x00, info_log);
      // todo log message

      free(info_log);
      LOGE("Error linking shader program %s", info_log);
    }

    glDeleteProgram(program_object);

    LOGE("init Succcess");
    
    return 0;
  }

  pd->program_object = program_object;

  glClearColor(1.0f, 1.0f, 1.0f, 1.0f);

  LOGE("Shader init success");
  
  return 1;
}


// draw the triangle using the above triangle shader
void draw(struct egl_context * context) {
  struct program_data * pd = context->shader_program_data;

  // LOGE("Drawing.. ");
  GLfloat vector_vertices [] =
    {
      0.0f, 0.5f, 0.0f,
      -0.5f, -0.5f, 0.0f,
      0.5f, -0.5f, 0.0f
    };

  // set the view port
  glViewport(0, 0, context->width, context->height);

  // clear the color buffer
  glClear(GL_COLOR_BUFFER_BIT);

  glUseProgram(pd->program_object);

  // load the vertex data
  glVertexAttribPointer (0, 3, GL_FLOAT, GL_FALSE, 0, vector_vertices);
  glEnableVertexAttribArray(0);

  glDrawArrays(GL_TRIANGLES, 0, 3);
}

void update(struct egl_context *context, float inteval) {
  // this is not neccessary for the static render (no animation)
}

void shutdown(struct egl_context * context) {
  struct program_data * pd = context->shader_program_data;
  glDeleteProgram(pd->program_object);
  free(context->shader_program_data);
}

